# Flutter Localization Configuration
# Diese Datei konfiguriert den ARB-Generator für nuuray_ui Package

arb-dir: lib/src/l10n
template-arb-file: app_de.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/src/generated/l10n
nullable-getter: false
preferred-supported-locales: [de]
